document.getElementById("myHeader").innerHTML = "<div class='header'>"+"<img id='heading' src='headerim.png'>"
+ "</div> <div class='navbar'> <a href='drgrwalker.html'>Home</a>" 
+ "<div class='projdropdown'>"
+ "<button class='projdropbtn'>Projects</button>"
+ "  <div class='projdropdown-content'>"
+ "<a href='codingprojects.html'>Coding Projects</a>"
+ "<a href='comedyprojects.html'>Comedy Shorts</a>"
+ "<a href='sewingprojects.html'>Sewing Projects</a>"
+ "<a href='artprojects.html'>Art Collections</a>"
+ "</div> </div> "
+ "<div class='hdropdown'>"
+ "<button class='homedropbtn'>About</button>"
+ "<div class='hdropdown-content'>"
+ "<a href='aboutpage.html#introsec'>Introduction</a>"
+ "<a href='aboutpage.html#researchsec'>Research Interests</a>"
+ "</div></div></div>"


document.getElementById("myFooter").innerHTML = "<div class='footer'>"
+  "Email: giannarasmussen2023@u.northwestern.edu &emsp;"
+ "Github: <a href='https://github.com/DrGeebWalker'>DrGeebWalker</a>"
+ "</div>"